# Generated by Django 4.1.2 on 2022-10-14 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asosiyapp', '0003_alter_mahsulot_olchov'),
        ('userapp', '0003_remove_sotuvchi_user_sotuvchi_user'),
        ('statsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Static',
            new_name='Statistika',
        ),
    ]
