# Generated by Django 4.1.2 on 2022-10-14 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_remove_sotuvchi_user_sotuvchi_user'),
        ('asosiyapp', '0003_alter_mahsulot_olchov'),
        ('statsapp', '0002_rename_static_statistika'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statistika',
            new_name='Static',
        ),
    ]
