# Generated by Django 4.1.2 on 2022-10-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiyapp', '0002_alter_mahsulot_kelgan_sana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsulot',
            name='olchov',
            field=models.CharField(default=0, max_length=40),
        ),
    ]
